baseURL = "https://linna-li.github.io"
languageCode = "en-us"
title = "Linna"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    since = 2020
    author = "linna.li"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "I am studying from zero"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "categories" # post or other

    google_verification = ""
   
    description = "Study Note" # site description
    keywords = "work server-side" # site keywords

    beian = ""
    baiduAnalytics = ""

[params.social]
    GitHub = "linna-li"
    Twitter = "lilinna5"
    Instagram = "lilinna2259"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    Facebook = "li.linna.73"
    Email = "linna9407@gmail.com"